# Generated by Django 5.1.5 on 2025-02-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(default='', max_length=200)),
                ('seller', models.CharField(default='', max_length=200)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=1)),
                ('servings_per_cont', models.IntegerField(default=1)),
                ('serving_size', models.FloatField(default=1)),
                ('mass', models.FloatField(default=1)),
                ('flavor', models.IntegerField()),
                ('favorite', models.BooleanField(default=False)),
                ('calories', models.FloatField()),
                ('total_fat', models.FloatField()),
                ('sat_fat', models.FloatField()),
                ('trans_fat', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('sodium', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fiber', models.FloatField()),
                ('total_sugar', models.FloatField()),
                ('added_sugar', models.FloatField()),
                ('protein', models.FloatField()),
            ],
        ),
    ]
